# StatClean Documentation
# Static HTML files, no Jekyll processing needed

title: StatClean
description: Comprehensive statistical data preprocessing and outlier detection library
url: "https://subaashnair.github.io"
baseurl: "/StatClean"

# Disable Jekyll processing for HTML files
plugins: []
markdown: kramdown
highlighter: rouge

github:
  repository_url: "https://github.com/SubaashNair/StatClean"